version: '3'
services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: galactic
    volumes:
      - galactic-volume:/var/lib/mysql
volumes:
  galactic-volume: