CREATE TABLE spaceships(
   Id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   Name VARCHAR(255) NOT NULL,
   Class VARCHAR(255) NOT NULL,
   Image VARCHAR(255) NOT NULL,
   Status VARCHAR(255) NOT NULL,
   Crew INT(11) UNSIGNED,
   Value BIGINT(11) UNSIGNED
);

CREATE TABLE armaments(
   Id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   spaceshipId INT(11) UNSIGNED,
   Title VARCHAR(255) NOT NULL UNIQUE,
   Qty INT(11) UNSIGNED
);

ALTER TABLE armaments
    ADD FOREIGN KEY (SpaceshipId) REFERENCES spaceships(Id);